FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["NotificationService/NotificationService.csproj", "NotificationService/"]
RUN dotnet restore "NotificationService/NotificationService.csproj"
COPY . .
WORKDIR "/src/NotificationService"
RUN dotnet build "NotificationService.csproj" -c Release -o /app/build

RUN dotnet new tool-manifest && dotnet tool install dotnet-ef --version 6.0.5
RUN dotnet ef migrations bundle

ENTRYPOINT ["./efbundle"]
